### ISSUE TITLE
[Question] Data update plans

### ISSUE THREAD

**Issue by corneliusroemer** [broadinstitute/pyro-cov#12]
Very cool project. I'm wondering whether you're planning to redo the analysis. Since last time, the number of sequences has almost doubled and there's a lot of new (labelled) diversity within Delta that could be interesting for the model to eat through.

On a different note: From a cursory glance at the paper, it seems that pango lineage classifications seem to have a fair impact on model results. I don't know whether you're aware that pango assignments have a significant error rate (false positives and negatives). This can be reduced by using `--usher` mode which uses a reference tree for classification instead of a decision tree. In any case, pango classifications cannot be taken as 100% correct. At least 1%, maybe more like 10% are wrong (in the currently used classifiers).

**Comment by fritzo** [comment]
Hi @corneliusroemer,

> whether you're planning to redo the analysis

Absolutely, we plan to update the results, sorry it's taking so long.  At the moment we're addressing comments from paper reviewers (e.g. running pangolin ourselves, changing the geographic partitioning scheme), and we're also working around increasingly noisy mutation calling by nextclade.

> using `--usher` mode

Thanks for the suggestion!  I'll add that to our pipeline.

**Comment by fritzo** [comment]
Hi @corneliusroemer, I've switched to `pangolin --usher` classification as you suggested, but I'm still blocked on cleaning up feature extraction.  Can I ask your advice here?

I'm trying to get a parsimoniously imputed set of mutations for each pango lineage.  One option is to pull them out of [usher's mutation-annoted tree](http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/), which is [easy to do](https://github.com/broadinstitute/pyro-cov/blob/c583c1fc0af5a2459b6a7e3aefcb4274c1ebe98c/pyrocov/usher.py#L16).  However usher treats deletions as missing data (treats '-' as 'N'), so we miss all the deletions.  Do you have any suggestions?

**Comment by corneliusroemer** [comment]
Regarding noisy data, what exactly do you mean by it? What's the nature of the noise? Problems with S:95/S:142 wobbliness, which is related to ARTIC amplicon dropout? Or other sorts of noise, like backfilling (particularly common in Turkish sequences). Or missing data?

Regarding Usher trees @angiehinrichs is the expert. One workaround for the problem with `- = N` could be to use Usher for the tree topology and Nextclade alignments as the data to do the imputation on.

Do you have an automated way to flag bad data entry, like wrong date? It happens quite a bit actually, I just came a cross a few sequences from Indonesia that said `2020` when it should have been `2021`. At Nextstrain we've got a script that does automatic outlier detection based on clock deviation, clade dates, private mutations, etc. Could be of interest.

**Comment by fritzo** [comment]
> what exactly do you mean by [noisy data]?

Our current phylogeny-unaware mutation calling process results in large differences between parent-child sets of mutations, especially for Delta lineages.  I haven't looked into the source of the noise, but I figured a phylogeny-aware parsimony-imputed approach would be better.

> use Usher for the tree topology and Nextclade alignments

Sounds reasonable :+1: Do the published [usher tree](http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/) or [pangolin tree](https://github.com/cov-lineages/pangoLEARN/blob/master/pangoLEARN/data/lineageTree.pb) have accession ids, so I could lookup each node's sequence in gisaid or genbank? Poking around I didn't see accession ids.

> Do you have an automated way to flag bad data ...?

We have a little logic, but could definitely improve.  Could you point to your outlier detection script?

**Comment by AngieHinrichs** [comment]
The [public UShER tree](http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/) includes GenBank accessions, except for COG-UK sequences not yet in ENA/GenBank as well as 253 sequences downloaded last year from the [China National Center for Bioinformation](https://ngdc.cncb.ac.cn/ncov/release_genome?lang=en) (those have accessions like CNA*, GWH*, NMDC*).  The tree distributed along with pangolin is a minimized version of the tree that does not contain real names/IDs.

If you have installed pangolin using conda, then you also have [matUtils](https://usher-wiki.readthedocs.io/en/latest/matUtils.html) which is handy for extracting information from UShER protobuf files.  To extract the sample names and accessions from the latest public UShER tree:
```
conda activate pangolin

matUtils extract -i public-latest.all.masked.pb -u public-latest.samples.txt

head public-latest.samples.txt
CHN/YN-0306-466/2020|MT396241.1|2020-03-06
DP0803|LC571037.1|2020-02-17
Northern_Ireland/NIRE-102322/2020|2020-03-23
Wales/PHWC-2707C/2020|2020-03-29
Scotland/CVR16/2020|2020-03-12
England/NOTT-10E58A/2020|2020-03-26
USA/CO-CDC-5607/2020|MT512430.1|2020-03-07
DP0687|LC571013.1|2020-02-17
USA/CA-QDX-2068/2020|MW190758.1|2020-03-17
USA/CA-QDX-2597/2020|MW191321.1|2020-03-16
```

To extract just the GenBank accessions:
```
grep -E '[A-Z]{2}[0-9]{6}\.[0-9]+' public-latest.samples.txt \
| awk -F\| '{ if ($3 == "") { print $1; } else { print $2; } }' > public-latest.genbank.txt
```
COG-UK provides FASTA and metadata for their latest sequences at https://www.cogconsortium.uk/tools-analysis/public-data-analysis-2/ (scroll down to "Latest sequence data").

I also maintain an UShER tree that includes GISAID sequences with EPI_ISL accessions, but I can't post that tree publicly due to GISAID restrictions.  I can share it privately with registered GISAID users who have agreed not to share GISAID data publicly.

**Comment by corneliusroemer** [comment]
Here's our `diagnostic.py` script that identifies outliers: https://github.com/neherlab/ncov-simple/blob/master/scripts/diagnostic.py

One important input is `clock_deviation` which is calculated in `ncov-ingest` here: 

https://github.com/nextstrain/ncov-ingest/blob/69d15f0ec3ee73a92b17face4d5465b33b6b151c/bin/join-metadata-and-clades#L107-L110
