### ISSUE TITLE
Changes neccesary for Nextclade update to v.1.10.0

### ISSUE THREAD

**Issue by corneliusroemer** [broadinstitute/pyro-cov#16]
I wanted to give you a small heads up. I found your repo through a quick code search, because it doesn't use `--input-dataset` for Nextclade run. Thus if you update to v1.10.0 (it was released yesterday), you will have to add a line. We recommend to use `--input-dataset`, but you can also add `--input-virus-properties` excplicitly.

See this issue for a detailed explanation: https://github.com/nextstrain/nextclade/issues/703

You need to make a change like here: https://github.com/broadinstitute/viral-pipelines/commit/97fd3397479366d7867a8fed6ee1a8cb3e0fa157

Sorry for the trouble.

**Comment by corneliusroemer** [comment]
Patch version 1.10.1 comes with a more helpful error message in this use case.

https://github.com/nextstrain/nextclade/releases/tag/1.10.1

Here are notes that should help migrating:

## Nextclade CLI 1.10.1 (2022-01-26)

### [Fix] Improve error message when the virus properties file is missing [#704](https://github.com/nextstrain/nextclade/pull/704)

Since version 1.10.0 Nextclade CLI have introduced a new required input file, `virus_properties.json` and [datasets](https://github.com/nextstrain/nextclade_data/blob/master/CHANGELOG.md) and [documentation](https://docs.nextstrain.org/projects/nextclade/) were updated to match. However, users who don't use datasets might have encountered breakage due to a missing file: when running Nextclade CLI without either `--input-dataset` of `--input-virus-properties` flag provided, it would stop with an unclear error message. In this release we improve the error message, making sure that that explains the problem and offers a solution.

This does not affect Nextclade Web or Nextalign CLI.

In order to facilitate upgrades, for most users, we recommend to:

 - download the latest dataset before each Nextclade CLI session (e.g. in the beginning of an automated workflow, or once you start a batch of experiments manually) using `nextclade dataset get` command
 - use `--input-dataset` flag instead of individual `--input-*` flags for dataset files when issuing `nextclade run` command
 - if necessary, override some of the individual input files using corresponding `--input-*` flags


### [Fix] Add information about `virus_properties.json` or `--input-virus-properties` to changelog

In the excitement of bringing the new features, we forgot to mention `virus_properties.json` or `--input-virus-properties` in the changelog when Nextclade CLI 1.10.0 was released. We now added this information retroactively.

**Comment by fritzo** [comment]
Thanks @corneliusroemer, we've switched from using nextclade to directly inputting usher trees.  I've removed all uses of nextclade in this repo.  I wish nextclade's interface had been a bit more stable, but anyway our ingest is about 100x cheaper now, thanks to the usher team 😄
