### ISSUE TITLE
sarscov2.py nuc_mutations_to_aa_mutations function

### ISSUE THREAD

**Issue by zwallace425** [broadinstitute/pyro-cov#20]
Hi,

I've been referring to your sarscov2.py code and I have a question about the [nuc_mutations_to_aa_mutations()](https://github.com/broadinstitute/pyro-cov/blob/5b09858a817dbe41b2a3604fa5c23370836861a3/pyrocov/sarscov2.py#L175) function: how is this function considering nucleotide mutations that might be occurring on the same codon?  The way I read it, It seems like the code finds how the new nucleotide allele alters the codon translation just one at a time.  So if you have something like A100T and then G102C that both occur on the same codon, the code finds the alternate amino acid for that same codon twice.

Also, to clarify one the steps in your pipeline, in preprocess_usher.py you're extracting the nucleotide mutations in a clade by parsing UShER's MAT and then feeding those nucleotide mutations into this nuc_mutations_to_aa_mutations() function?  Are you not able to extract the amino acid mutations directly from UShER's MAT?

Thanks!

**Comment by fritzo** [comment]
Hi @zwallace425 we welcome PRs consisting of merely clarifying code comments 😄 

> how is this function considering nucleotide mutations that might be occurring on the same codon?

It looks like the first loop `for m in ms:` groups nucleotide mutations by codon.  Then the second loop `for (gene, position_aa), ms in ms_b_aa.items()` applies a set `ms` of nucleotide mutations all to a single codon. For example if A100T and G102C appear in the same codon, they will both appear in a single `ms` list.  In each pass through that second loop we start with an `old_codon`, apply all mutations, then read off the `new_codon`. If they correspond to different amino acids, we emit that as a substitution.

> in preprocess_usher.py you're extracting the nucleotide mutations in a clade by parsing UShER's MAT and then feeding those nucleotide mutations into this nuc_mutations_to_aa_mutations() function?

Correct.

> Are you not able to extract the amino acid mutations directly from UShER's MAT?

Not sure I understand how you'd intend to extract the information directly. MATs are optimized for minimum information and do not contain amino-acid level information. Here's their beautifully simple schema: https://github.com/yatisht/usher/blob/master/parsimony.proto

**Comment by zwallace425** [comment]
Ahh I see it now, thanks @fritzo !

And regarding the MATs, it wasn't clear to me if extracting amino acid information was an option, but doesn't seem like it is, so I'll stick with the nuc_mutations_to_aa_mutations route.
