### ISSUE TITLE
preprocess Error

### ISSUE THREAD

**Issue by Rezwanuzzaman** [broadinstitute/pyro-cov#21]
Hello, I'm attempting to run the 'make preprocess' command but receiving the error shown below.

/pyro-cov$ make preprocess
python scripts/preprocess_usher.py
    34644 Refining a tree with 3009506 nodes
Traceback (most recent call last):
  File "scripts/preprocess_usher.py", line 455, in <module>
    main(args)
  File "scripts/preprocess_usher.py", line 413, in main
    fine_to_coarse = refine_mutation_tree(coarse_proto, fine_proto)
  File "/***/pyro-cov/pyrocov/usher.py", line 138, in refine_mutation_tree
    fine_to_coarse[fine] = pangolin.compress(meta.clade)
  File "/***/pyro-cov/pyrocov/pangolin.py", line 154, in compress
    assert re.match(r"^[A-Z]+(\.[0-9]+)*$", result), result
AssertionError: proposed464
Makefile:52: recipe for target 'preprocess' failed
make: *** [preprocess] Error 1

Suggest if any !!!

**Comment by fritzo** [comment]
Hi @Rezwanuzzaman, it looks like one of the usher clades is labeled by `proposed464` rather than a pango lineage designation like `AY.4.2`. Is this custom data, or did you download the standard usher tree from the usher website? If this is standard data, then you could exit early from `refine_mutation_tree` with a warning.

**Comment by corneliusroemer** [comment]
@AngieHinrichs has started annotating proposed recombinants on the official Usher tree.

So a change in your scripts may be necessary @fritzo

**Comment by AngieHinrichs** [comment]
Sorry for the inconvenience @fritzo and @Rezwanuzzaman!  And thanks for flagging that @corneliusroemer.  

I hope you can ignore the proposed lineages, but if not (or if this turns out to be a problem for others) then I could look into making separate files with and without those.

**Comment by fritzo** [comment]
Thanks for explaining @corneliusroemer and @AngieHinrichs, I've updated the preprocessing script to ignore the non-PANGOlineage nodes in the usher tree.
