### ISSUE TITLE
Runtime Error in Analyze Step

### ISSUE THREAD

**Issue by ai4pharma** [broadinstitute/pyro-cov#23]
Got following error message in this step, it seems related to tensor dimension, anything related to the version of pytorch? 
```bash
python scripts/mutrans.py --vary-holdout
```
   509512 step 10000 L=12.7628 RS=0.08 IS=1.46 RLS=0.0165 ILS=96.8
```bash
Traceback (most recent call last):
  File "./python3.8/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "./python3.8/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "./python3.8/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "mutrans.py", line 541, in model
    pc_rate_loc = rate_loc.expand(P, C).reshape(-1)
RuntimeError: expand(torch.cuda.FloatTensor{[1000, 1, 1, 1, 3000]}, size=[5, 3000]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (5)
```

**Comment by fritzo** [comment]
What is the meaning of the dimension of size 1000?  Are we drawing 1000 samples?

I've seen errors like this when attempting to draw vectorized samples from a model that does not support vectorization.  The Pyro-cov model does not support vectorization, but last I checked we never attempt to draw vectorized samples from it, instead we sequentially draw 1000 samples.

**Comment by kjshan** [comment]
Hi, everyone. I have the same issue, have you fixed it? how to deal with it?

**Comment by sweety919** [comment]
Hello, I met the same issue here. Could you tell me the method to deal with it if you have solved this problem?

**Comment by fritzo** [comment]
I think this tensor shape error could be fixed by avoiding vectorization in `predict()`. Here's an attempted fix: https://github.com/broadinstitute/pyro-cov/pull/53

**Comment by wxsh1213** [comment]
Hi, I have the same issue. Does anyone know how to fix it?
