### ISSUE TITLE
Episcore vs PyR0

### ISSUE THREAD

**Issue by Shicheng-Guo** [broadinstitute/pyro-cov#24]
Did we try to compare the performance between Episcore vs PyR0? 

https://pubmed.ncbi.nlm.nih.gov/33114416/

Thanks. 

Shicheng

**Comment by fritzo** [comment]
These two methods predict different things and cannot be compared.  Episcore predicts the severity of viral infection based on health features of the human individual admitted to a hospital.  PyR0 predicts the relative growth rate of a viral strain in a human pupulation, based on the genome of the virus and the context of other viral strains in a given region.
