### ISSUE TITLE
Pango Lineage code error

### ISSUE THREAD

**Issue by ShaneSchroeder** [broadinstitute/pyro-cov#55]
I have run into an issue when trying to run PyR0 during the analysis step. The Pango lineages that are checked for in the program [here](https://github.com/broadinstitute/pyro-cov/blob/master/pyrocov/pangolin.py) are out of date and crashes because it tries to check a lineage that is not included in their dictionary (e.g. "XAA"). 

Pango has an updated list [here](https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json) but their dictionary sometimes refers to something like "XAA": ["BA.1*","BA.2*"] instead of the standard form of something like "L": "B.1.1.10" where a single code corresponds to one specific lineage rather than a list.

The main issue is when it is evaluating a lineage with a code with 3 letters and starts with X (which is required to be evaluated to my understanding), it cannot proceed. This is due to the values for that code being a list that does not refer to any specific lineages but just all sublineages that start with some specific lineage codes. 

Traceback for current pango dictionary:

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/76157271/219471629-21b1d5b9-0354-424a-ab03-d2adf7ad116a.png">

Traceback for updated pango dictionary:

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/76157271/219477101-012af3b7-ec19-45c5-8755-924296e4d71f.png">

Is there an updated Pango lineage dictionary to use that has specific lineages for the X** codes or is there a plan for an improved pangolin.py version in the future?

**Comment by fritzo** [comment]
IIRC @bkotzen added some handling of recombinant lineages like this, but I don't know the details.

pyro-cov should download the latests pango dictionary from their github repo, so I suspect this is less an issue with stale dictionaries and more an issue with handling recombination.

**Comment by bkotzen** [comment]
Right, I believe the issue stems from choosing a parent; I've set up a branch that loads recombinants and randomly chooses one parent to be the designated parent. @ShaneSchroeder try checking out the branch bkotzen-bug-fixes or bkotzen-improvements. I believe recombinants are handled in both those branches.

**Comment by ShaneSchroeder** [comment]
@fritzo @bkotzen I used pangolin.py from the bkotzen-bug-fixes branch and that has solved my issue, thank you!
