### ISSUE TITLE
Error in make preprocess

### ISSUE THREAD

**Issue by smruti241** [broadinstitute/pyro-cov#56]
Hi @fritzo , thanks for the nice work you all have done. It is really helpful. While doing this, I am getting error in the preprocess step. Can you please guide me where to change the script to get the results. The error is given below:
(genslm) smrutip@iiitd:~/smruti/smruti_project/pyro-cov$ make preprocess
python scripts/preprocess_usher.py
    88881 Refining a tree with 5368614 nodes
   127725 Found 1464458 clones
   127762 Refined 3002 -> 3904156
   133841 Loading usher metadata
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8228934/8228934 [01:10<00:00, 117364.63it/s]
   213595 Found metadata:
{'day': 8222240, 'lineage': 8228933, 'location': 3437048}
   213783 Loading nextstrain metadata
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8604565/8604565 [01:31<00:00, 94178.42it/s]
   395045 Found metadata:
{'location': 7373072, 'day': 7986935, 'lineage': 8004755}
   434744 Loading tree from results/lineageTree.fine.pb
   506458 Accumulating mutations on 5368614 nodes
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5368614/5368614 [00:46<00:00, 115729.55it/s]
  1093872 Found 8229415 samples in the usher tree
  1093873 Skipped 4792648 nodes because:
Counter({'no location': 4785167, 'no date': 7481})
  1093873 Kept 3436767 rows
  1096118 Saved results/columns.pkl
  1096133 Saved results/stats.pkl
  1103242 Extracting features with 2000 clades
  1269283 Pruning 5365612/5368614 nodes
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5365612/5365612 [00:56<00:00, 94689.75it/s]
Traceback (most recent call last):
  File "scripts/preprocess_usher.py", line 456, in <module>
    main(args)
  File "scripts/preprocess_usher.py", line 428, in main
    extract_features(
  File "scripts/preprocess_usher.py", line 368, in extract_features
    assert len(clade_set) <= max_num_clades
AssertionError
make: *** [Makefile:55: preprocess] Error 1

Please let me know. Thanks!

**Comment by smruti241** [comment]
@barkasn , @martinjankowiak , @JacobLemieux , @bkotzen , @corneliusroemer Please look into this and let me know. Thanks!

**Comment by MaxLiu245** [comment]
Hi @smruti241 , I met the same case you described here and I could offer you a trick to avoid it although I didn't figure it out either.

The `AssertionError` occurs because your `len(clade_set)` > `max_num_clades` in function `extract_features`. Note that there's a line `max_num_clades = max(max_num_clades, len(coarse_to_fine))` in a function called `prune_tree` in `extract_features`. Here `max_num_clades` actually becomes larger in the function `prune_tree` and thus makes the output of `prune_tree` longer. Finally `clade_set` becomes longer and the `AssertionError` occurs.

I just delete this line to avoid this error but I don't know whether this matters either (QwQ...

**Comment by bkotzen** [comment]
I have done the same as @MaxLiu245 and haven't had any issues since.

**Comment by smruti241** [comment]
I have done as @MaxLiu245 said and I didnt face any issue. Thanks!

**Comment by smruti241** [comment]
@MaxLiu245 , @bkotzen can you please look into this error #60 because I am facing issue in make analyze. Did you face the same issue? Thanks!
